export default [
    {
        title:'vue',
        name:['重命名','移动到','复制','分享','标星','加密'],
        shanc:[
            {
                tit:'删除',
                nam:['确定删除吗']
            }
        ]
    },
    {
        title:'react',
        name:['重命名','移动到','复制','分享','标星','加密'],
        shanc:[
            {
                tit:'删除',
                nam:['确定删除吗']
            }
        ]
    },
    {
        title:'nodejs',
        name:['重命名','移动到','复制','分享','标星','加密'],
        shanc:[
            {
                tit:'删除',
                nam:['确定删除吗']
            }
        ]
    }
]